version: '3'

services:
  audit:
    build: 
      context: .
      dockerfile: Dockerfile
    image: chimpwizardstools/vscode-fat-ide
    ports:
        - '8080:8080'   
    environment:
      PASSWORD: 'admin'
